-- 01 - SET DATABASE CONTEXT.
--CREATE DATABASE ps_spadedm;
USE SCHEMA PS_SPADEDM.PUBLIC;

-- 02 - CREATE A SHARE OBJECT
CREATE SHARE PLURALSIGHT_COURSES_SHARE;

-- 03 - CREATE A TABLE AND INSERT SOME DATA
CREATE OR REPLACE TABLE PLURALSIGHT_COURSES
(
ID INT,
URL VARCHAR,
AUTHOR_NAME VARCHAR,
SUBJECT VARCHAR,
STATUS VARCHAR
);

INSERT INTO PLURALSIGHT_COURSES VALUES('1','https://www.pluralsight.com/courses/snowpro-core-data-protection-sharing','Pinal Dave','Snowflake','Completed');
INSERT INTO  PLURALSIGHT_COURSES VALUES('2','https://www.pluralsight.com/courses/snowpro-advanced-data-analyst-data-ingestion-preparation-cert','Bismark Adomako','Snowflake','Completed');
INSERT INTO  PLURALSIGHT_COURSES VALUES('3','https://www.pluralsight.com/courses/snowpro-advanced-data-analyst-transformation-modeling-cert','Ian Fogelman','Snowflake','Completed');
INSERT INTO  PLURALSIGHT_COURSES VALUES('4','https://www.pluralsight.com/courses/c-sharp-10-playbook','Simon Robinson','C#','Completed');
INSERT INTO  PLURALSIGHT_COURSES VALUES('5','https://www.pluralsight.com/courses/c-sharp-tips-traps','Jason Roberts','C#','Completed');
INSERT INTO  PLURALSIGHT_COURSES VALUES('6','https://www.pluralsight.com/courses/tableau-desktop-manipulating-data','Adam Crahen','Tableau','Completed');
INSERT INTO  PLURALSIGHT_COURSES VALUES('7','https://www.pluralsight.com/courses/powershell-scripting-getting-started','Liam Cleary','Powershell','Completed');

-- 04 - CREATE A SECURE VIEW
CREATE OR REPLACE SECURE VIEW SECURE_VIEW_EXAMPLE AS
SELECT ID,
URL,
AUTHOR_NAME,
SUBJECT,
STATUS
FROM PS_SPADEDM.PUBLIC.PLURALSIGHT_COURSES;

-- 05 - GRANT USAGE AND SELECT PERMISSION ON THE SECURE VIEW TO THE SHARE
GRANT USAGE ON DATABASE PS_SPADEDM TO SHARE PLURALSIGHT_COURSES_SHARE;
GRANT USAGE ON SCHEMA PUBLIC TO SHARE PLURALSIGHT_COURSES_SHARE;
GRANT SELECT ON VIEW PS_SPADEDM.PUBLIC.SECURE_VIEW_EXAMPLE TO SHARE PLURALSIGHT_COURSES_SHARE;

-- 06 - ALTER THE SHARE AND ADD AN EXTERNAL ACCOUNT LOCATOR.
ALTER SHARE PLURALSIGHT_COURSES_SHARE ADD ACCOUNT = JWB24600;

-- 07 VIEW SHARE DETAILS
SHOW SHARES;

DESC SHARE PLURALSIGHT_COURSES_SHARE;

SHOW GRANTS ON SHARE PLURALSIGHT_COURSES_SHARE;

-- 08 - IN ANOTHER ACCOUNT CREATE A DATABASE FROM THE SHARE 
CREATE DATABASE PLURALSIGHT_COURSES_SHARED FROM SHARE ZBPUGGR.NEB11824.PLURALSIGHT_COURSES_SHARE;

SELECT * FROM PLURALSIGHT_COURSES_SHARED.SECURE_VIEW_EXAMPLE;

-- LIMITATIONS / CONSIDERATIONS
-- SHARED DATABASES ARE READ ONLY
-- ACCOUNTS CONSUMING A SHARE CANNOT RE-SHARE THE SHARED DATABASE
-- CLONES AND TIMETRAVEL ARE NOT SUPPORTED
